basePath: /
consumes:
- application/json
definitions:
  Product:
    description: Product product
    properties:
      desc:
        description: description
        type: string
        x-go-name: Description
      id:
        description: ID
        format: int64
        type: integer
        x-go-name: ID
      name:
        description: name
        type: string
        x-go-name: Name
      price:
        description: price
        format: float
        type: number
        x-go-name: Price
      sku:
        description: s k u
        type: string
        x-go-name: SKU
    type: object
    x-go-package: github.com/progmatic-99/microService/models
info:
  description: Documentation for Product API
  title: Product API
  version: 1.0.0
paths:
  /:
    get:
      description: Returns a list of products
      operationId: listProducts
      responses:
        "200":
          $ref: '#/responses/productsResponse'
      tags:
      - products
  /{id}:
    delete:
      operationId: deleteProduct
      parameters:
      - description: ID of the product to be deleted.
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "201":
          $ref: '#/responses/noContent'
      summary: Returns nothing.
      tags:
      - products
produces:
- application/json
responses:
  noContent:
    description: ""
  productsResponse:
    description: A list of products
    schema:
      items:
        $ref: '#/definitions/Product'
      type: array
schemes:
- http
swagger: "2.0"
